services:
  devcamp:
    image: docker.io/ahmeeddhon/devcamp25:docker-imgtag
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - devcamp_net

  load_balancer:
    image: nginx:stable-alpine-perl
    volumes:
      - .nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80
    depends_on:
      - devcamp
    networks:
      - devcamp_net

networks:
  devcamp_net: